{
 "title": "NEs Dashboard",
 "time": { "from": "2024-01-03T08:15:18.694Z", "to": "2024-02-28T08:15:18.702Z" },
 "templating": {
  "list": [
   { "name": "vendor", "label": "Vendor", "query": "Nokia, Cisco" },
   {
    "name": "Region",
    "label": "Select Region",
    "query": "SELECT region\nFROM grafana_dashboards.ne_inventory WHERE region = 'DXB' OR region = 'AUH' OR region = 'NE';"
   },
   { "name": "equipmentType", "label": "Network Layer", "query": "AGG,CSG,PREAGG" },
   {
    "name": "softwareVersion",
    "label": "softwareVersion",
    "query": "SELECT DISTINCT softwareVersion\nFROM grafana_dashboards.ne_inventory;"
   },
   {
    "name": "softwareVsChassis",
    "query": "SELECT GROUP_CONCAT(DISTINCT chassisType) AS chassisTypes\nFROM grafana_dashboards.ne_inventory\nWHERE softwareVersion IN $softwareVersion AND region IN $Region GROUP BY softwareVersion;"
   }
  ]
 },
 "panels": [
  {
   "title": "NEs (Region: $Region)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "demodb",
     "rawSql": "SELECT COUNT(*) AS Total\r\nFROM grafana_dashboards.ne_inventory\r\nWHERE equipmentType IN ('AGG', 'PREAGG', 'CSG') AND region IN ($Region) AND product in ($vendor);"
    },
    {
     "dataset": "demodb",
     "rawSql": "SELECT COUNT(*) AS AGG\r\nFROM grafana_dashboards.ne_inventory\r\nWHERE equipmentType IN ('AGG') AND region IN ($Region) AND product in ($vendor);"
    },
    {
     "dataset": "demodb",
     "rawSql": "SELECT COUNT(*) AS PREAGG\r\nFROM grafana_dashboards.ne_inventory\r\nWHERE equipmentType IN ('PREAGG') AND region IN ($Region) AND product in ($vendor);"
    },
    {
     "dataset": "demodb",
     "rawSql": "SELECT COUNT(*) AS CSG\r\nFROM grafana_dashboards.ne_inventory\r\nWHERE equipmentType IN ('CSG') AND region IN ($Region) AND product in ($vendor);"
    }
   ]
  },
  {
   "title": "Chassis Type  (Region: $Region, NW Layer: $equipmentType)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "dataset": "demodb",
     "rawSql": "SELECT chassisType, COUNT(*) total\r\nFROM grafana_dashboards.ne_inventory\r\nWHERE equipmentType IN ($equipmentType) AND region IN ($Region)  AND product in ($vendor) GROUP BY chassisType  ORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "SW Version (Region: $Region, NW Layer: $equipmentType)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "demodb",
     "rawSql": "SELECT softwareVersion, COUNT(*) AS Total\r\nFROM grafana_dashboards.ne_inventory\r\nWHERE equipmentType IN ($equipmentType) AND region IN ($Region)  AND product in ($vendor) GROUP BY softwareVersion ORDER BY Total DESC;;\r\n"
    }
   ]
  },
  {
   "title": "Chassis Type versus SW Version (Region: $Region, NW Layer: $equipmentType) ",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "demodb",
     "rawSql": "SELECT\r\n    subquery.chassisType,\r\n    subquery.softwareVersion,  \r\n    subquery.SoftwareVersionCount,\r\n    subquery.ExpiredStatus,\r\n    CONCAT(subquery.SoftwareVersionCount, subquery.ExpiredStatus) AS data\r\nFROM (\r\n    SELECT \r\n        chassisType,\r\n        softwareVersion AS softwareVersion,  \r\n        COUNT(*) AS SoftwareVersionCount,\r\n        CASE\r\n            WHEN expiredDate < CURDATE() THEN '[EX]'\r\n            WHEN expiredDate <= CURDATE() + INTERVAL 180 DAY THEN '[GTE]'\r\n            WHEN expiredDate IS NULL OR expiredDate = '' THEN ''\r\n            ELSE ''\r\n        END AS ExpiredStatus\r\n    FROM\r\n        grafana_dashboards.ne_inventory\r\n    WHERE equipmentType IN ($equipmentType) AND region IN ($Region)   AND product in ($vendor)\r\n    GROUP BY\r\n        chassisType, softwareVersion\r\n) AS subquery;"
    }
   ]
  }
 ]
}